name: educonnect
description: "A comprehensive Flutter-based educational platform that facilitates communication and learning between students, instructors, and administrators."

publish_to: "none" 
version: 1.0.0+1

environment:
  sdk: ^3.8.1


dependencies:
  flutter:
    sdk: flutter

  # UI & Icons
  cupertino_icons: ^1.0.8          # iOS-style icons and design elements
  flutter_svg: ^2.2.0              # SVG asset support for scalable graphics
  salomon_bottom_bar: ^3.3.2       # Custom bottom navigation component
  easy_image_viewer: ^1.5.1        # Enhanced image viewing component

  # State Management
  flutter_riverpod: ^2.6.1         # Primary state management solution

  # Backend Services - Firebase
  firebase_core: ^4.0.0            # Firebase base configuration
  firebase_auth: ^6.0.0            # User authentication and authorization
  cloud_firestore: ^6.0.0          # NoSQL database for real-time data

  # Backend Services - Supabase
  supabase_flutter: ^2.9.1         # Secondary backend service and storage

  # Media & Storage
  image_picker: ^1.0.4             # Image selection from gallery and camera
  sqflite: ^2.4.2                  # Local SQLite database for offline functionality

  # Utilities
  intl: ^0.20.2                    # Internationalization and localization support

dev_dependencies:
  flutter_test:
    sdk: flutter

  # The "flutter_lints" package below contains a set of recommended lints to
  # encourage good coding practices. The lint set provided by the package is
  # activated in the `analysis_options.yaml` file located at the root of your
  # package. See that file for information about deactivating specific lint
  # rules and activating additional ones.
  flutter_lints: ^6.0.0
  
  # Testing
  mockito: ^5.4.4                  # Mock generation for unit testing
  build_runner: ^2.4.13            # Code generation tool



# The following section is specific to Flutter packages.
flutter:
 
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/vectors/pana.svg
    - assets/vectors/400-Error-Bad-Request-pana.svg
    - assets/vectors/404-Error-Page-not-Found-with-people-connecting-a-plug-pana.svg
    - assets/vectors/No-data-amico.svg
    - assets/vectors/Loading-pana.svg
    - assets/vectors/post-Skeleton Loader.svg
    - assets/vectors/announcement-Skeleton Loader.svg
    - assets/vectors/course.svg
    - assets/images/default_avatar.png

  