// Mocks generated by Mockito 5.4.6 from annotations
// in educonnect/test/integration/enrollment_notification_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i3;
import 'dart:io' as _i10;

import 'package:cloud_firestore/cloud_firestore.dart' as _i6;
import 'package:educonnect/core/result.dart' as _i4;
import 'package:educonnect/modules/course.dart' as _i5;
import 'package:educonnect/modules/user.dart' as _i8;
import 'package:educonnect/repositories/course_repository.dart' as _i2;
import 'package:educonnect/repositories/user_repository.dart' as _i9;
import 'package:mockito/mockito.dart' as _i1;
import 'package:mockito/src/dummies.dart' as _i7;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

/// A class which mocks [CourseRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockCourseRepository extends _i1.Mock implements _i2.CourseRepository {
  MockCourseRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.Future<_i4.Result<List<_i5.Course>>> getCourses({
    int? limit = 10,
    _i6.DocumentSnapshot<Object?>? lastDocument,
    _i5.CourseStatus? status,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#getCourses, [], {
              #limit: limit,
              #lastDocument: lastDocument,
              #status: status,
            }),
            returnValue: _i3.Future<_i4.Result<List<_i5.Course>>>.value(
              _i7.dummyValue<_i4.Result<List<_i5.Course>>>(
                this,
                Invocation.method(#getCourses, [], {
                  #limit: limit,
                  #lastDocument: lastDocument,
                  #status: status,
                }),
              ),
            ),
          )
          as _i3.Future<_i4.Result<List<_i5.Course>>>);

  @override
  _i3.Future<_i4.Result<List<_i5.Course>>> getInstructorCourses({
    required String? instructorId,
    int? limit = 10,
    _i6.DocumentSnapshot<Object?>? lastDocument,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#getInstructorCourses, [], {
              #instructorId: instructorId,
              #limit: limit,
              #lastDocument: lastDocument,
            }),
            returnValue: _i3.Future<_i4.Result<List<_i5.Course>>>.value(
              _i7.dummyValue<_i4.Result<List<_i5.Course>>>(
                this,
                Invocation.method(#getInstructorCourses, [], {
                  #instructorId: instructorId,
                  #limit: limit,
                  #lastDocument: lastDocument,
                }),
              ),
            ),
          )
          as _i3.Future<_i4.Result<List<_i5.Course>>>);

  @override
  _i3.Future<_i4.Result<List<_i5.Course>>> getEnrolledCourses({
    required String? studentId,
    int? limit = 10,
    _i6.DocumentSnapshot<Object?>? lastDocument,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#getEnrolledCourses, [], {
              #studentId: studentId,
              #limit: limit,
              #lastDocument: lastDocument,
            }),
            returnValue: _i3.Future<_i4.Result<List<_i5.Course>>>.value(
              _i7.dummyValue<_i4.Result<List<_i5.Course>>>(
                this,
                Invocation.method(#getEnrolledCourses, [], {
                  #studentId: studentId,
                  #limit: limit,
                  #lastDocument: lastDocument,
                }),
              ),
            ),
          )
          as _i3.Future<_i4.Result<List<_i5.Course>>>);

  @override
  _i3.Future<_i4.Result<_i5.Course>> getCourseById(String? courseId) =>
      (super.noSuchMethod(
            Invocation.method(#getCourseById, [courseId]),
            returnValue: _i3.Future<_i4.Result<_i5.Course>>.value(
              _i7.dummyValue<_i4.Result<_i5.Course>>(
                this,
                Invocation.method(#getCourseById, [courseId]),
              ),
            ),
          )
          as _i3.Future<_i4.Result<_i5.Course>>);

  @override
  _i3.Future<_i4.Result<_i5.Course>> createCourse(_i5.Course? course) =>
      (super.noSuchMethod(
            Invocation.method(#createCourse, [course]),
            returnValue: _i3.Future<_i4.Result<_i5.Course>>.value(
              _i7.dummyValue<_i4.Result<_i5.Course>>(
                this,
                Invocation.method(#createCourse, [course]),
              ),
            ),
          )
          as _i3.Future<_i4.Result<_i5.Course>>);

  @override
  _i3.Future<_i4.Result<_i5.Course>> updateCourse(_i5.Course? course) =>
      (super.noSuchMethod(
            Invocation.method(#updateCourse, [course]),
            returnValue: _i3.Future<_i4.Result<_i5.Course>>.value(
              _i7.dummyValue<_i4.Result<_i5.Course>>(
                this,
                Invocation.method(#updateCourse, [course]),
              ),
            ),
          )
          as _i3.Future<_i4.Result<_i5.Course>>);

  @override
  _i3.Future<_i4.Result<void>> deleteCourse(String? courseId) =>
      (super.noSuchMethod(
            Invocation.method(#deleteCourse, [courseId]),
            returnValue: _i3.Future<_i4.Result<void>>.value(
              _i7.dummyValue<_i4.Result<void>>(
                this,
                Invocation.method(#deleteCourse, [courseId]),
              ),
            ),
          )
          as _i3.Future<_i4.Result<void>>);

  @override
  _i3.Future<_i4.Result<void>> enrollStudent(
    String? courseId,
    String? studentId,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#enrollStudent, [courseId, studentId]),
            returnValue: _i3.Future<_i4.Result<void>>.value(
              _i7.dummyValue<_i4.Result<void>>(
                this,
                Invocation.method(#enrollStudent, [courseId, studentId]),
              ),
            ),
          )
          as _i3.Future<_i4.Result<void>>);

  @override
  _i3.Future<_i4.Result<void>> unenrollStudent(
    String? courseId,
    String? studentId,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#unenrollStudent, [courseId, studentId]),
            returnValue: _i3.Future<_i4.Result<void>>.value(
              _i7.dummyValue<_i4.Result<void>>(
                this,
                Invocation.method(#unenrollStudent, [courseId, studentId]),
              ),
            ),
          )
          as _i3.Future<_i4.Result<void>>);

  @override
  _i3.Future<_i4.Result<List<_i8.User>>> getEnrolledStudents(
    String? courseId,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#getEnrolledStudents, [courseId]),
            returnValue: _i3.Future<_i4.Result<List<_i8.User>>>.value(
              _i7.dummyValue<_i4.Result<List<_i8.User>>>(
                this,
                Invocation.method(#getEnrolledStudents, [courseId]),
              ),
            ),
          )
          as _i3.Future<_i4.Result<List<_i8.User>>>);

  @override
  _i3.Future<_i4.Result<bool>> isStudentEnrolled(
    String? courseId,
    String? studentId,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#isStudentEnrolled, [courseId, studentId]),
            returnValue: _i3.Future<_i4.Result<bool>>.value(
              _i7.dummyValue<_i4.Result<bool>>(
                this,
                Invocation.method(#isStudentEnrolled, [courseId, studentId]),
              ),
            ),
          )
          as _i3.Future<_i4.Result<bool>>);

  @override
  _i3.Future<_i4.Result<Map<String, int>>> getCourseStatistics(
    String? courseId,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#getCourseStatistics, [courseId]),
            returnValue: _i3.Future<_i4.Result<Map<String, int>>>.value(
              _i7.dummyValue<_i4.Result<Map<String, int>>>(
                this,
                Invocation.method(#getCourseStatistics, [courseId]),
              ),
            ),
          )
          as _i3.Future<_i4.Result<Map<String, int>>>);

  @override
  _i3.Future<_i4.Result<List<_i5.Course>>> searchCourses(String? query) =>
      (super.noSuchMethod(
            Invocation.method(#searchCourses, [query]),
            returnValue: _i3.Future<_i4.Result<List<_i5.Course>>>.value(
              _i7.dummyValue<_i4.Result<List<_i5.Course>>>(
                this,
                Invocation.method(#searchCourses, [query]),
              ),
            ),
          )
          as _i3.Future<_i4.Result<List<_i5.Course>>>);

  @override
  _i3.Future<_i4.Result<List<_i5.Course>>> getCoursesByCategory(
    String? category,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#getCoursesByCategory, [category]),
            returnValue: _i3.Future<_i4.Result<List<_i5.Course>>>.value(
              _i7.dummyValue<_i4.Result<List<_i5.Course>>>(
                this,
                Invocation.method(#getCoursesByCategory, [category]),
              ),
            ),
          )
          as _i3.Future<_i4.Result<List<_i5.Course>>>);

  @override
  _i3.Future<_i4.Result<List<_i5.Course>>> getCoursesByStatus(
    _i5.CourseStatus? status,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#getCoursesByStatus, [status]),
            returnValue: _i3.Future<_i4.Result<List<_i5.Course>>>.value(
              _i7.dummyValue<_i4.Result<List<_i5.Course>>>(
                this,
                Invocation.method(#getCoursesByStatus, [status]),
              ),
            ),
          )
          as _i3.Future<_i4.Result<List<_i5.Course>>>);

  @override
  _i3.Future<_i4.Result<List<_i5.Course>>> getPopularCourses({
    int? limit = 10,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#getPopularCourses, [], {#limit: limit}),
            returnValue: _i3.Future<_i4.Result<List<_i5.Course>>>.value(
              _i7.dummyValue<_i4.Result<List<_i5.Course>>>(
                this,
                Invocation.method(#getPopularCourses, [], {#limit: limit}),
              ),
            ),
          )
          as _i3.Future<_i4.Result<List<_i5.Course>>>);

  @override
  _i3.Future<_i4.Result<List<_i5.Course>>> getRecentCourses({
    int? limit = 10,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#getRecentCourses, [], {#limit: limit}),
            returnValue: _i3.Future<_i4.Result<List<_i5.Course>>>.value(
              _i7.dummyValue<_i4.Result<List<_i5.Course>>>(
                this,
                Invocation.method(#getRecentCourses, [], {#limit: limit}),
              ),
            ),
          )
          as _i3.Future<_i4.Result<List<_i5.Course>>>);

  @override
  _i3.Future<_i4.Result<_i5.Course>> updateCourseStatus(
    String? courseId,
    _i5.CourseStatus? status,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#updateCourseStatus, [courseId, status]),
            returnValue: _i3.Future<_i4.Result<_i5.Course>>.value(
              _i7.dummyValue<_i4.Result<_i5.Course>>(
                this,
                Invocation.method(#updateCourseStatus, [courseId, status]),
              ),
            ),
          )
          as _i3.Future<_i4.Result<_i5.Course>>);

  @override
  _i3.Stream<List<_i5.Course>> getCoursesStream({int? limit = 10}) =>
      (super.noSuchMethod(
            Invocation.method(#getCoursesStream, [], {#limit: limit}),
            returnValue: _i3.Stream<List<_i5.Course>>.empty(),
          )
          as _i3.Stream<List<_i5.Course>>);

  @override
  _i3.Stream<List<_i8.User>> getEnrolledStudentsStream(String? courseId) =>
      (super.noSuchMethod(
            Invocation.method(#getEnrolledStudentsStream, [courseId]),
            returnValue: _i3.Stream<List<_i8.User>>.empty(),
          )
          as _i3.Stream<List<_i8.User>>);

  @override
  _i3.Future<_i4.Result<bool>> isEnrollmentAvailable(String? courseId) =>
      (super.noSuchMethod(
            Invocation.method(#isEnrollmentAvailable, [courseId]),
            returnValue: _i3.Future<_i4.Result<bool>>.value(
              _i7.dummyValue<_i4.Result<bool>>(
                this,
                Invocation.method(#isEnrollmentAvailable, [courseId]),
              ),
            ),
          )
          as _i3.Future<_i4.Result<bool>>);

  @override
  _i3.Future<_i4.Result<List<String>>> getCourseCategories() =>
      (super.noSuchMethod(
            Invocation.method(#getCourseCategories, []),
            returnValue: _i3.Future<_i4.Result<List<String>>>.value(
              _i7.dummyValue<_i4.Result<List<String>>>(
                this,
                Invocation.method(#getCourseCategories, []),
              ),
            ),
          )
          as _i3.Future<_i4.Result<List<String>>>);
}

/// A class which mocks [UserRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockUserRepository extends _i1.Mock implements _i9.UserRepository {
  MockUserRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.Future<_i4.Result<_i8.User>> getUserById(String? userId) =>
      (super.noSuchMethod(
            Invocation.method(#getUserById, [userId]),
            returnValue: _i3.Future<_i4.Result<_i8.User>>.value(
              _i7.dummyValue<_i4.Result<_i8.User>>(
                this,
                Invocation.method(#getUserById, [userId]),
              ),
            ),
          )
          as _i3.Future<_i4.Result<_i8.User>>);

  @override
  _i3.Future<_i4.Result<_i8.User>> updateUser(_i8.User? user) =>
      (super.noSuchMethod(
            Invocation.method(#updateUser, [user]),
            returnValue: _i3.Future<_i4.Result<_i8.User>>.value(
              _i7.dummyValue<_i4.Result<_i8.User>>(
                this,
                Invocation.method(#updateUser, [user]),
              ),
            ),
          )
          as _i3.Future<_i4.Result<_i8.User>>);

  @override
  _i3.Future<_i4.Result<String>> uploadProfileImage(
    _i10.File? image,
    String? userId,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#uploadProfileImage, [image, userId]),
            returnValue: _i3.Future<_i4.Result<String>>.value(
              _i7.dummyValue<_i4.Result<String>>(
                this,
                Invocation.method(#uploadProfileImage, [image, userId]),
              ),
            ),
          )
          as _i3.Future<_i4.Result<String>>);

  @override
  _i3.Future<_i4.Result<void>> deleteProfileImage(String? userId) =>
      (super.noSuchMethod(
            Invocation.method(#deleteProfileImage, [userId]),
            returnValue: _i3.Future<_i4.Result<void>>.value(
              _i7.dummyValue<_i4.Result<void>>(
                this,
                Invocation.method(#deleteProfileImage, [userId]),
              ),
            ),
          )
          as _i3.Future<_i4.Result<void>>);

  @override
  _i3.Future<_i4.Result<List<_i8.User>>> searchUsers(String? query) =>
      (super.noSuchMethod(
            Invocation.method(#searchUsers, [query]),
            returnValue: _i3.Future<_i4.Result<List<_i8.User>>>.value(
              _i7.dummyValue<_i4.Result<List<_i8.User>>>(
                this,
                Invocation.method(#searchUsers, [query]),
              ),
            ),
          )
          as _i3.Future<_i4.Result<List<_i8.User>>>);

  @override
  _i3.Future<_i4.Result<List<_i8.User>>> getUsersByRole(_i8.UserRole? role) =>
      (super.noSuchMethod(
            Invocation.method(#getUsersByRole, [role]),
            returnValue: _i3.Future<_i4.Result<List<_i8.User>>>.value(
              _i7.dummyValue<_i4.Result<List<_i8.User>>>(
                this,
                Invocation.method(#getUsersByRole, [role]),
              ),
            ),
          )
          as _i3.Future<_i4.Result<List<_i8.User>>>);

  @override
  _i3.Future<_i4.Result<void>> toggleBookmark(String? userId, String? postId) =>
      (super.noSuchMethod(
            Invocation.method(#toggleBookmark, [userId, postId]),
            returnValue: _i3.Future<_i4.Result<void>>.value(
              _i7.dummyValue<_i4.Result<void>>(
                this,
                Invocation.method(#toggleBookmark, [userId, postId]),
              ),
            ),
          )
          as _i3.Future<_i4.Result<void>>);

  @override
  _i3.Future<_i4.Result<List<String>>> getBookmarks(String? userId) =>
      (super.noSuchMethod(
            Invocation.method(#getBookmarks, [userId]),
            returnValue: _i3.Future<_i4.Result<List<String>>>.value(
              _i7.dummyValue<_i4.Result<List<String>>>(
                this,
                Invocation.method(#getBookmarks, [userId]),
              ),
            ),
          )
          as _i3.Future<_i4.Result<List<String>>>);

  @override
  _i3.Future<_i4.Result<void>> updateLikedPosts(
    String? userId,
    List<String>? likedPosts,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#updateLikedPosts, [userId, likedPosts]),
            returnValue: _i3.Future<_i4.Result<void>>.value(
              _i7.dummyValue<_i4.Result<void>>(
                this,
                Invocation.method(#updateLikedPosts, [userId, likedPosts]),
              ),
            ),
          )
          as _i3.Future<_i4.Result<void>>);

  @override
  _i3.Future<_i4.Result<void>> enrollInCourse(
    String? userId,
    String? courseId,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#enrollInCourse, [userId, courseId]),
            returnValue: _i3.Future<_i4.Result<void>>.value(
              _i7.dummyValue<_i4.Result<void>>(
                this,
                Invocation.method(#enrollInCourse, [userId, courseId]),
              ),
            ),
          )
          as _i3.Future<_i4.Result<void>>);

  @override
  _i3.Future<_i4.Result<void>> unenrollFromCourse(
    String? userId,
    String? courseId,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#unenrollFromCourse, [userId, courseId]),
            returnValue: _i3.Future<_i4.Result<void>>.value(
              _i7.dummyValue<_i4.Result<void>>(
                this,
                Invocation.method(#unenrollFromCourse, [userId, courseId]),
              ),
            ),
          )
          as _i3.Future<_i4.Result<void>>);

  @override
  _i3.Future<_i4.Result<List<String>>> getEnrolledCourses(String? userId) =>
      (super.noSuchMethod(
            Invocation.method(#getEnrolledCourses, [userId]),
            returnValue: _i3.Future<_i4.Result<List<String>>>.value(
              _i7.dummyValue<_i4.Result<List<String>>>(
                this,
                Invocation.method(#getEnrolledCourses, [userId]),
              ),
            ),
          )
          as _i3.Future<_i4.Result<List<String>>>);

  @override
  _i3.Future<_i4.Result<_i8.User>> createUser(_i8.User? user) =>
      (super.noSuchMethod(
            Invocation.method(#createUser, [user]),
            returnValue: _i3.Future<_i4.Result<_i8.User>>.value(
              _i7.dummyValue<_i4.Result<_i8.User>>(
                this,
                Invocation.method(#createUser, [user]),
              ),
            ),
          )
          as _i3.Future<_i4.Result<_i8.User>>);

  @override
  _i3.Future<_i4.Result<void>> deleteUser(String? userId) =>
      (super.noSuchMethod(
            Invocation.method(#deleteUser, [userId]),
            returnValue: _i3.Future<_i4.Result<void>>.value(
              _i7.dummyValue<_i4.Result<void>>(
                this,
                Invocation.method(#deleteUser, [userId]),
              ),
            ),
          )
          as _i3.Future<_i4.Result<void>>);

  @override
  _i3.Future<_i4.Result<bool>> userExists(String? userId) =>
      (super.noSuchMethod(
            Invocation.method(#userExists, [userId]),
            returnValue: _i3.Future<_i4.Result<bool>>.value(
              _i7.dummyValue<_i4.Result<bool>>(
                this,
                Invocation.method(#userExists, [userId]),
              ),
            ),
          )
          as _i3.Future<_i4.Result<bool>>);

  @override
  _i3.Future<_i4.Result<Map<String, int>>> getUserStatistics(String? userId) =>
      (super.noSuchMethod(
            Invocation.method(#getUserStatistics, [userId]),
            returnValue: _i3.Future<_i4.Result<Map<String, int>>>.value(
              _i7.dummyValue<_i4.Result<Map<String, int>>>(
                this,
                Invocation.method(#getUserStatistics, [userId]),
              ),
            ),
          )
          as _i3.Future<_i4.Result<Map<String, int>>>);
}
